using ConsumingFaysalBankService;
using Microsoft.SqlServer.Server;
using MigraDoc.DocumentObjectModel;
using MigraDoc.DocumentObjectModel.Tables;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Xml;

namespace ParsingXml
{
    class Program
    {
        static void Main(string[] args)
        {
            string s = @"<DtStatement>
<Statement>
	<SERIALNO>3.00</SERIALNO>
	<CARDSERIALNO>2222222.003</CARDSERIALNO>
	<STMPARTCODE>CCT1</STMPARTCODE>
	<STMPARTDESC> Credit Card Trsanction Detail</STMPARTDESC>
	<MESSAGEOFTHEMONTH></MESSAGEOFTHEMONTH>
	<STMSTARTDATE></STMSTARTDATE>
	<STMENDDATE></STMENDDATE>
	<CONUMBER></CONUMBER>
	<CREDITCARDNO>5338380244435861</CREDITCARDNO>
	<CUSTOMERNAME></CUSTOMERNAME>
	<ADDRESS1></ADDRESS1>
	<ADDRESS2></ADDRESS2>
	<ADDRESS3></ADDRESS3>
	<PRODUCTNAME></PRODUCTNAME>
	<STATEMENTDATE></STATEMENTDATE>
	<APR></APR>
	<PAYMENTDUEDATE></PAYMENTDUEDATE>
	<OPENINGBALANCE>0.00</OPENINGBALANCE>
	<TRANSACTIONDATE>2022-11-29T00:00:00</TRANSACTIONDATE>
	<POSTINGDATE>2022-11-29T00:00:00</POSTINGDATE>
	<DESCRIPTIONREFERENCE>1bill Payment Charges - 17-Nov-22</DESCRIPTIONREFERENCE>
	<TRANSACTIONAMOUNTUSD>10.00</TRANSACTIONAMOUNTUSD>
	<TRANSACTIONAMOUNTPKR>10.00</TRANSACTIONAMOUNTPKR>
	<RUNNINGBALANCEPKR>12.00</RUNNINGBALANCEPKR>
	<CLOSINGBALANCEDATE></CLOSINGBALANCEDATE>
	<PROFIT_RECOVERED></PROFIT_RECOVERED>
	<MWM_PAYMENT></MWM_PAYMENT>
	<ISL_CONV_FLAG></ISL_CONV_FLAG>
</Statement>

<Statement>
	<SERIALNO>4.00</SERIALNO>
	<CARDSERIALNO>2222222.004</CARDSERIALNO>
	<STMPARTCODE>CCT1</STMPARTCODE>
	<STMPARTDESC> Credit Card Trsanction Detail</STMPARTDESC>
	<MESSAGEOFTHEMONTH></MESSAGEOFTHEMONTH>
	<STMSTARTDATE></STMSTARTDATE>
	<STMENDDATE></STMENDDATE>
	<CONUMBER></CONUMBER>
	<CREDITCARDNO>5338380244435861</CREDITCARDNO>
	<CUSTOMERNAME></CUSTOMERNAME>
	<ADDRESS1></ADDRESS1>
	<ADDRESS2></ADDRESS2>
	<ADDRESS3></ADDRESS3>
	<PRODUCTNAME></PRODUCTNAME>
	<STATEMENTDATE></STATEMENTDATE>
	<APR></APR>
	<PAYMENTDUEDATE></PAYMENTDUEDATE>
	<OPENINGBALANCE>0.00</OPENINGBALANCE>
	<TRANSACTIONDATE>2022-12-04T00:00:00</TRANSACTIONDATE>
	<POSTINGDATE>2022-12-07T00:00:00</POSTINGDATE>
	<DESCRIPTIONREFERENCE>Food Panda Karachi Pkpk</DESCRIPTIONREFERENCE>
	<TRANSACTIONAMOUNTUSD>758.99</TRANSACTIONAMOUNTUSD>
	<TRANSACTIONAMOUNTPKR>758.99</TRANSACTIONAMOUNTPKR>
	<RUNNINGBALANCEPKR>770.99</RUNNINGBALANCEPKR>
	<CLOSINGBALANCEDATE></CLOSINGBALANCEDATE>
	<PROFIT_RECOVERED></PROFIT_RECOVERED>
	<MWM_PAYMENT></MWM_PAYMENT>
	<ISL_CONV_FLAG></ISL_CONV_FLAG>
</Statement>

<Statement>
	<SERIALNO>5.00</SERIALNO>
	<CARDSERIALNO>2222222.005</CARDSERIALNO>
	<STMPARTCODE>CCT1</STMPARTCODE>
	<STMPARTDESC> Credit Card Trsanction Detail</STMPARTDESC>
	<MESSAGEOFTHEMONTH></MESSAGEOFTHEMONTH>
	<STMSTARTDATE></STMSTARTDATE>
	<STMENDDATE></STMENDDATE>
	<CONUMBER></CONUMBER>
	<CREDITCARDNO>5338380244435861</CREDITCARDNO>
	<CUSTOMERNAME></CUSTOMERNAME>
	<ADDRESS1></ADDRESS1>
	<ADDRESS2></ADDRESS2>
	<ADDRESS3></ADDRESS3>
	<PRODUCTNAME></PRODUCTNAME>
	<STATEMENTDATE></STATEMENTDATE>
	<APR></APR>
	<PAYMENTDUEDATE></PAYMENTDUEDATE>
	<OPENINGBALANCE>0.00</OPENINGBALANCE>
	<TRANSACTIONDATE>2022-12-07T00:00:00</TRANSACTIONDATE>
	<POSTINGDATE>2022-12-07T00:00:00</POSTINGDATE>
	<DESCRIPTIONREFERENCE>Reversal Of 3% Gst -Sindh Stc (Amend)</DESCRIPTIONREFERENCE>
	<TRANSACTIONAMOUNTUSD>-21.30</TRANSACTIONAMOUNTUSD>
	<TRANSACTIONAMOUNTPKR>-21.30</TRANSACTIONAMOUNTPKR>
	<RUNNINGBALANCEPKR>749.69</RUNNINGBALANCEPKR>
	<CLOSINGBALANCEDATE></CLOSINGBALANCEDATE>
	<PROFIT_RECOVERED></PROFIT_RECOVERED>
	<MWM_PAYMENT></MWM_PAYMENT>
	<ISL_CONV_FLAG></ISL_CONV_FLAG>
</Statement>

<Statement>
	<SERIALNO>6.00</SERIALNO>
	<CARDSERIALNO>2222222.006</CARDSERIALNO>
	<STMPARTCODE>CCT1</STMPARTCODE>
	<STMPARTDESC> Credit Card Trsanction Detail</STMPARTDESC>
	<MESSAGEOFTHEMONTH></MESSAGEOFTHEMONTH>
	<STMSTARTDATE></STMSTARTDATE>
	<STMENDDATE></STMENDDATE>
	<CONUMBER></CONUMBER>
	<CREDITCARDNO>5338380244435861</CREDITCARDNO>
	<CUSTOMERNAME></CUSTOMERNAME>
	<ADDRESS1></ADDRESS1>
	<ADDRESS2></ADDRESS2>
	<ADDRESS3></ADDRESS3>
	<PRODUCTNAME></PRODUCTNAME>
	<STATEMENTDATE></STATEMENTDATE>
	<APR></APR>
	<PAYMENTDUEDATE></PAYMENTDUEDATE>
	<OPENINGBALANCE>0.00</OPENINGBALANCE>
	<TRANSACTIONDATE>2022-12-10T00:00:00</TRANSACTIONDATE>
	<POSTINGDATE>2022-12-10T00:00:00</POSTINGDATE>
	<DESCRIPTIONREFERENCE>Finance Charge</DESCRIPTIONREFERENCE>
	<TRANSACTIONAMOUNTUSD>2007.00</TRANSACTIONAMOUNTUSD>
	<TRANSACTIONAMOUNTPKR>2007.00</TRANSACTIONAMOUNTPKR>
	<RUNNINGBALANCEPKR>2756.69</RUNNINGBALANCEPKR>
	<CLOSINGBALANCEDATE></CLOSINGBALANCEDATE>
	<PROFIT_RECOVERED></PROFIT_RECOVERED>
	<MWM_PAYMENT></MWM_PAYMENT>
	<ISL_CONV_FLAG></ISL_CONV_FLAG>
</Statement>

<Statement>
	<SERIALNO>7.00</SERIALNO>
	<CARDSERIALNO>2222222.007</CARDSERIALNO>
	<STMPARTCODE>CCT1</STMPARTCODE>
	<STMPARTDESC> Credit Card Trsanction Detail</STMPARTDESC>
	<MESSAGEOFTHEMONTH></MESSAGEOFTHEMONTH>
	<STMSTARTDATE></STMSTARTDATE>
	<STMENDDATE></STMENDDATE>
	<CONUMBER></CONUMBER>
	<CREDITCARDNO>5338380244435861</CREDITCARDNO>
	<CUSTOMERNAME></CUSTOMERNAME>
	<ADDRESS1></ADDRESS1>
	<ADDRESS2></ADDRESS2>
	<ADDRESS3></ADDRESS3>
	<PRODUCTNAME></PRODUCTNAME>
	<STATEMENTDATE></STATEMENTDATE>
	<APR></APR>
	<PAYMENTDUEDATE></PAYMENTDUEDATE>
	<OPENINGBALANCE>0.00</OPENINGBALANCE>
	<TRANSACTIONDATE>2022-12-10T00:00:00</TRANSACTIONDATE>
	<POSTINGDATE>2022-12-10T00:00:00</POSTINGDATE>
	<DESCRIPTIONREFERENCE>Retail Transfer Amt 219646.521/12</DESCRIPTIONREFERENCE>
	<TRANSACTIONAMOUNTUSD>19967.86</TRANSACTIONAMOUNTUSD>
	<TRANSACTIONAMOUNTPKR>19967.86</TRANSACTIONAMOUNTPKR>
	<RUNNINGBALANCEPKR>22724.55</RUNNINGBALANCEPKR>
	<CLOSINGBALANCEDATE></CLOSINGBALANCEDATE>
	<PROFIT_RECOVERED></PROFIT_RECOVERED>
	<MWM_PAYMENT></MWM_PAYMENT>
	<ISL_CONV_FLAG></ISL_CONV_FLAG>
</Statement>

<Statement>
	<SERIALNO>8.00</SERIALNO>
	<CARDSERIALNO>2222222.008</CARDSERIALNO>
	<STMPARTCODE>CCT1</STMPARTCODE>
	<STMPARTDESC> Credit Card Trsanction Detail</STMPARTDESC>
	<MESSAGEOFTHEMONTH></MESSAGEOFTHEMONTH>
	<STMSTARTDATE></STMSTARTDATE>
	<STMENDDATE></STMENDDATE>
	<CONUMBER></CONUMBER>
	<CREDITCARDNO>5338380244435861</CREDITCARDNO>
	<CUSTOMERNAME></CUSTOMERNAME>
	<ADDRESS1></ADDRESS1>
	<ADDRESS2></ADDRESS2>
	<ADDRESS3></ADDRESS3>
	<PRODUCTNAME></PRODUCTNAME>
	<STATEMENTDATE></STATEMENTDATE>
	<APR></APR>
	<PAYMENTDUEDATE></PAYMENTDUEDATE>
	<OPENINGBALANCE>0.00</OPENINGBALANCE>
	<TRANSACTIONDATE>2022-12-12T00:00:00</TRANSACTIONDATE>
	<POSTINGDATE>2022-12-15T00:00:00</POSTINGDATE>
	<DESCRIPTIONREFERENCE>Food Panda Karachi Pkpk</DESCRIPTIONREFERENCE>
	<TRANSACTIONAMOUNTUSD>768.99</TRANSACTIONAMOUNTUSD>
	<TRANSACTIONAMOUNTPKR>768.99</TRANSACTIONAMOUNTPKR>
	<RUNNINGBALANCEPKR>23493.54</RUNNINGBALANCEPKR>
	<CLOSINGBALANCEDATE></CLOSINGBALANCEDATE>
	<PROFIT_RECOVERED></PROFIT_RECOVERED>
	<MWM_PAYMENT></MWM_PAYMENT>
	<ISL_CONV_FLAG></ISL_CONV_FLAG>
</Statement>

<Statement>
	<SERIALNO>9.00</SERIALNO>
	<CARDSERIALNO>2222222.009</CARDSERIALNO>
	<STMPARTCODE>CCT1</STMPARTCODE>
	<STMPARTDESC> Credit Card Trsanction Detail</STMPARTDESC>
	<MESSAGEOFTHEMONTH></MESSAGEOFTHEMONTH>
	<STMSTARTDATE></STMSTARTDATE>
	<STMENDDATE></STMENDDATE>
	<CONUMBER></CONUMBER>
	<CREDITCARDNO>5338380244435861</CREDITCARDNO>
	<CUSTOMERNAME></CUSTOMERNAME>
	<ADDRESS1></ADDRESS1>
	<ADDRESS2></ADDRESS2>
	<ADDRESS3></ADDRESS3>
	<PRODUCTNAME></PRODUCTNAME>
	<STATEMENTDATE></STATEMENTDATE>
	<APR></APR>
	<PAYMENTDUEDATE></PAYMENTDUEDATE>
	<OPENINGBALANCE>0.00</OPENINGBALANCE>
	<TRANSACTIONDATE>2022-12-28T00:00:00</TRANSACTIONDATE>
	<POSTINGDATE>2022-12-28T00:00:00</POSTINGDATE>
	<DESCRIPTIONREFERENCE>Cc-Payment Dr Act Without Chq</DESCRIPTIONREFERENCE>
	<TRANSACTIONAMOUNTUSD>-26168.00</TRANSACTIONAMOUNTUSD>
	<TRANSACTIONAMOUNTPKR>-26168.00</TRANSACTIONAMOUNTPKR>
	<RUNNINGBALANCEPKR>-2674.46</RUNNINGBALANCEPKR>
	<CLOSINGBALANCEDATE></CLOSINGBALANCEDATE>
	<PROFIT_RECOVERED></PROFIT_RECOVERED>
	<MWM_PAYMENT></MWM_PAYMENT>
	<ISL_CONV_FLAG></ISL_CONV_FLAG>
</Statement>

<Statement>
	<SERIALNO>10.00</SERIALNO>
	<CARDSERIALNO>2222222.01</CARDSERIALNO>
	<STMPARTCODE>CCT1</STMPARTCODE>
	<STMPARTDESC> Credit Card Trsanction Detail</STMPARTDESC>
	<MESSAGEOFTHEMONTH></MESSAGEOFTHEMONTH>
	<STMSTARTDATE></STMSTARTDATE>
	<STMENDDATE></STMENDDATE>
	<CONUMBER></CONUMBER>
	<CREDITCARDNO>5338380244435861</CREDITCARDNO>
	<CUSTOMERNAME></CUSTOMERNAME>
	<ADDRESS1></ADDRESS1>
	<ADDRESS2></ADDRESS2>
	<ADDRESS3></ADDRESS3>
	<PRODUCTNAME></PRODUCTNAME>
	<STATEMENTDATE></STATEMENTDATE>
	<APR></APR>
	<PAYMENTDUEDATE></PAYMENTDUEDATE>
	<OPENINGBALANCE>0.00</OPENINGBALANCE>
	<TRANSACTIONDATE>2022-12-30T00:00:00</TRANSACTIONDATE>
	<POSTINGDATE>2023-01-02T00:00:00</POSTINGDATE>
	<DESCRIPTIONREFERENCE>Pie In The Sky Karachi Pkpk</DESCRIPTIONREFERENCE>
	<TRANSACTIONAMOUNTUSD>1000.00</TRANSACTIONAMOUNTUSD>
	<TRANSACTIONAMOUNTPKR>1000.00</TRANSACTIONAMOUNTPKR>
	<RUNNINGBALANCEPKR>-1674.46</RUNNINGBALANCEPKR>
	<CLOSINGBALANCEDATE></CLOSINGBALANCEDATE>
	<PROFIT_RECOVERED></PROFIT_RECOVERED>
	<MWM_PAYMENT></MWM_PAYMENT>
	<ISL_CONV_FLAG></ISL_CONV_FLAG>
</Statement>

<Statement>
	<SERIALNO>11.00</SERIALNO>
	<CARDSERIALNO>2222222.011</CARDSERIALNO>
	<STMPARTCODE>CCT1</STMPARTCODE>
	<STMPARTDESC> Credit Card Trsanction Detail</STMPARTDESC>
	<MESSAGEOFTHEMONTH></MESSAGEOFTHEMONTH>
	<STMSTARTDATE></STMSTARTDATE>
	<STMENDDATE></STMENDDATE>
	<CONUMBER></CONUMBER>
	<CREDITCARDNO>5338380244435861</CREDITCARDNO>
	<CUSTOMERNAME></CUSTOMERNAME>
	<ADDRESS1></ADDRESS1>
	<ADDRESS2></ADDRESS2>
	<ADDRESS3></ADDRESS3>
	<PRODUCTNAME></PRODUCTNAME>
	<STATEMENTDATE></STATEMENTDATE>
	<APR></APR>
	<PAYMENTDUEDATE></PAYMENTDUEDATE>
	<OPENINGBALANCE>0.00</OPENINGBALANCE>
	<TRANSACTIONDATE>2022-12-30T00:00:00</TRANSACTIONDATE>
	<POSTINGDATE>2023-01-02T00:00:00</POSTINGDATE>
	<DESCRIPTIONREFERENCE>Pie In The Sky Karachi Pkpk</DESCRIPTIONREFERENCE>
	<TRANSACTIONAMOUNTUSD>970.00</TRANSACTIONAMOUNTUSD>
	<TRANSACTIONAMOUNTPKR>970.00</TRANSACTIONAMOUNTPKR>
	<RUNNINGBALANCEPKR>-704.46</RUNNINGBALANCEPKR>
	<CLOSINGBALANCEDATE></CLOSINGBALANCEDATE>
	<PROFIT_RECOVERED></PROFIT_RECOVERED>
	<MWM_PAYMENT></MWM_PAYMENT>
	<ISL_CONV_FLAG></ISL_CONV_FLAG>
</Statement>

<Statement>
	<SERIALNO>12.00</SERIALNO>
	<CARDSERIALNO>2222222.012</CARDSERIALNO>
	<STMPARTCODE>CCT1</STMPARTCODE>
	<STMPARTDESC> Credit Card Trsanction Detail</STMPARTDESC>
	<MESSAGEOFTHEMONTH></MESSAGEOFTHEMONTH>
	<STMSTARTDATE></STMSTARTDATE>
	<STMENDDATE></STMENDDATE>
	<CONUMBER></CONUMBER>
	<CREDITCARDNO>5338380244435861</CREDITCARDNO>
	<CUSTOMERNAME></CUSTOMERNAME>
	<ADDRESS1></ADDRESS1>
	<ADDRESS2></ADDRESS2>
	<ADDRESS3></ADDRESS3>
	<PRODUCTNAME></PRODUCTNAME>
	<STATEMENTDATE></STATEMENTDATE>
	<APR></APR>
	<PAYMENTDUEDATE></PAYMENTDUEDATE>
	<OPENINGBALANCE>0.00</OPENINGBALANCE>
	<TRANSACTIONDATE>2023-01-01T00:00:00</TRANSACTIONDATE>
	<POSTINGDATE>2023-01-04T00:00:00</POSTINGDATE>
	<DESCRIPTIONREFERENCE>Chase Karachi Pkpk</DESCRIPTIONREFERENCE>
	<TRANSACTIONAMOUNTUSD>5685.00</TRANSACTIONAMOUNTUSD>
	<TRANSACTIONAMOUNTPKR>5685.00</TRANSACTIONAMOUNTPKR>
	<RUNNINGBALANCEPKR>4980.54</RUNNINGBALANCEPKR>
	<CLOSINGBALANCEDATE></CLOSINGBALANCEDATE>
	<PROFIT_RECOVERED></PROFIT_RECOVERED>
	<MWM_PAYMENT></MWM_PAYMENT>
	<ISL_CONV_FLAG></ISL_CONV_FLAG>
</Statement>

<Statement>
	<SERIALNO>13.00</SERIALNO>
	<CARDSERIALNO>2222222.013</CARDSERIALNO>
	<STMPARTCODE>CCT1</STMPARTCODE>
	<STMPARTDESC> Credit Card Trsanction Detail</STMPARTDESC>
	<MESSAGEOFTHEMONTH></MESSAGEOFTHEMONTH>
	<STMSTARTDATE></STMSTARTDATE>
	<STMENDDATE></STMENDDATE>
	<CONUMBER></CONUMBER>
	<CREDITCARDNO>5338380244435861</CREDITCARDNO>
	<CUSTOMERNAME></CUSTOMERNAME>
	<ADDRESS1></ADDRESS1>
	<ADDRESS2></ADDRESS2>
	<ADDRESS3></ADDRESS3>
	<PRODUCTNAME></PRODUCTNAME>
	<STATEMENTDATE></STATEMENTDATE>
	<APR></APR>
	<PAYMENTDUEDATE></PAYMENTDUEDATE>
	<OPENINGBALANCE>0.00</OPENINGBALANCE>
	<TRANSACTIONDATE>2023-01-01T00:00:00</TRANSACTIONDATE>
	<POSTINGDATE>2023-01-04T00:00:00</POSTINGDATE>
	<DESCRIPTIONREFERENCE>Kababjees Bakers Karachi Pkpk</DESCRIPTIONREFERENCE>
	<TRANSACTIONAMOUNTUSD>1851.00</TRANSACTIONAMOUNTUSD>
	<TRANSACTIONAMOUNTPKR>1851.00</TRANSACTIONAMOUNTPKR>
	<RUNNINGBALANCEPKR>6831.54</RUNNINGBALANCEPKR>
	<CLOSINGBALANCEDATE></CLOSINGBALANCEDATE>
	<PROFIT_RECOVERED></PROFIT_RECOVERED>
	<MWM_PAYMENT></MWM_PAYMENT>
	<ISL_CONV_FLAG></ISL_CONV_FLAG>
</Statement>

<Statement>
	<SERIALNO>14.00</SERIALNO>
	<CARDSERIALNO>2222222.014</CARDSERIALNO>
	<STMPARTCODE>CCT1</STMPARTCODE>
	<STMPARTDESC> Credit Card Trsanction Detail</STMPARTDESC>
	<MESSAGEOFTHEMONTH></MESSAGEOFTHEMONTH>
	<STMSTARTDATE></STMSTARTDATE>
	<STMENDDATE></STMENDDATE>
	<CONUMBER></CONUMBER>
	<CREDITCARDNO>5338380244435861</CREDITCARDNO>
	<CUSTOMERNAME></CUSTOMERNAME>
	<ADDRESS1></ADDRESS1>
	<ADDRESS2></ADDRESS2>
	<ADDRESS3></ADDRESS3>
	<PRODUCTNAME></PRODUCTNAME>
	<STATEMENTDATE></STATEMENTDATE>
	<APR></APR>
	<PAYMENTDUEDATE></PAYMENTDUEDATE>
	<OPENINGBALANCE>0.00</OPENINGBALANCE>
	<TRANSACTIONDATE>2023-01-10T00:00:00</TRANSACTIONDATE>
	<POSTINGDATE>2023-01-10T00:00:00</POSTINGDATE>
	<DESCRIPTIONREFERENCE>Chip Fee</DESCRIPTIONREFERENCE>
	<TRANSACTIONAMOUNTUSD>1000.00</TRANSACTIONAMOUNTUSD>
	<TRANSACTIONAMOUNTPKR>1000.00</TRANSACTIONAMOUNTPKR>
	<RUNNINGBALANCEPKR>7831.54</RUNNINGBALANCEPKR>
	<CLOSINGBALANCEDATE></CLOSINGBALANCEDATE>
	<PROFIT_RECOVERED></PROFIT_RECOVERED>
	<MWM_PAYMENT></MWM_PAYMENT>
	<ISL_CONV_FLAG></ISL_CONV_FLAG>
</Statement>

<Statement>
	<SERIALNO>15.00</SERIALNO>
	<CARDSERIALNO>2222222.015</CARDSERIALNO>
	<STMPARTCODE>CCT1</STMPARTCODE>
	<STMPARTDESC> Credit Card Trsanction Detail</STMPARTDESC>
	<MESSAGEOFTHEMONTH></MESSAGEOFTHEMONTH>
	<STMSTARTDATE></STMSTARTDATE>
	<STMENDDATE></STMENDDATE>
	<CONUMBER></CONUMBER>
	<CREDITCARDNO>5338380244435861</CREDITCARDNO>
	<CUSTOMERNAME></CUSTOMERNAME>
	<ADDRESS1></ADDRESS1>
	<ADDRESS2></ADDRESS2>
	<ADDRESS3></ADDRESS3>
	<PRODUCTNAME></PRODUCTNAME>
	<STATEMENTDATE></STATEMENTDATE>
	<APR></APR>
	<PAYMENTDUEDATE></PAYMENTDUEDATE>
	<OPENINGBALANCE>0.00</OPENINGBALANCE>
	<TRANSACTIONDATE>2023-01-10T00:00:00</TRANSACTIONDATE>
	<POSTINGDATE>2023-01-10T00:00:00</POSTINGDATE>
	<DESCRIPTIONREFERENCE>Pip Accrued Profit - Retail Transfer Amt</DESCRIPTIONREFERENCE>
	<TRANSACTIONAMOUNTUSD>8348.00</TRANSACTIONAMOUNTUSD>
	<TRANSACTIONAMOUNTPKR>8348.00</TRANSACTIONAMOUNTPKR>
	<RUNNINGBALANCEPKR>16179.54</RUNNINGBALANCEPKR>
	<CLOSINGBALANCEDATE></CLOSINGBALANCEDATE>
	<PROFIT_RECOVERED></PROFIT_RECOVERED>
	<MWM_PAYMENT></MWM_PAYMENT>
	<ISL_CONV_FLAG></ISL_CONV_FLAG>
</Statement>

<Statement>
	<SERIALNO>16.00</SERIALNO>
	<CARDSERIALNO>2222222.016</CARDSERIALNO>
	<STMPARTCODE>CCT1</STMPARTCODE>
	<STMPARTDESC> Credit Card Trsanction Detail</STMPARTDESC>
	<MESSAGEOFTHEMONTH></MESSAGEOFTHEMONTH>
	<STMSTARTDATE></STMSTARTDATE>
	<STMENDDATE></STMENDDATE>
	<CONUMBER></CONUMBER>
	<CREDITCARDNO>5338380244435861</CREDITCARDNO>
	<CUSTOMERNAME></CUSTOMERNAME>
	<ADDRESS1></ADDRESS1>
	<ADDRESS2></ADDRESS2>
	<ADDRESS3></ADDRESS3>
	<PRODUCTNAME></PRODUCTNAME>
	<STATEMENTDATE></STATEMENTDATE>
	<APR></APR>
	<PAYMENTDUEDATE></PAYMENTDUEDATE>
	<OPENINGBALANCE>0.00</OPENINGBALANCE>
	<TRANSACTIONDATE>2023-01-10T00:00:00</TRANSACTIONDATE>
	<POSTINGDATE>2023-01-10T00:00:00</POSTINGDATE>
	<DESCRIPTIONREFERENCE>Retail Transfer Amt 199678.662/12</DESCRIPTIONREFERENCE>
	<TRANSACTIONAMOUNTUSD>19967.86</TRANSACTIONAMOUNTUSD>
	<TRANSACTIONAMOUNTPKR>19967.86</TRANSACTIONAMOUNTPKR>
	<RUNNINGBALANCEPKR>36147.40</RUNNINGBALANCEPKR>
	<CLOSINGBALANCEDATE></CLOSINGBALANCEDATE>
	<PROFIT_RECOVERED></PROFIT_RECOVERED>
	<MWM_PAYMENT></MWM_PAYMENT>
	<ISL_CONV_FLAG></ISL_CONV_FLAG>
</Statement>

<Statement>
	<SERIALNO>17.00</SERIALNO>
	<CARDSERIALNO>2222222.017</CARDSERIALNO>
	<STMPARTCODE>CCT1</STMPARTCODE>
	<STMPARTDESC> Credit Card Trsanction Detail</STMPARTDESC>
	<MESSAGEOFTHEMONTH></MESSAGEOFTHEMONTH>
	<STMSTARTDATE></STMSTARTDATE>
	<STMENDDATE></STMENDDATE>
	<CONUMBER></CONUMBER>
	<CREDITCARDNO>5338380244435861</CREDITCARDNO>
	<CUSTOMERNAME></CUSTOMERNAME>
	<ADDRESS1></ADDRESS1>
	<ADDRESS2></ADDRESS2>
	<ADDRESS3></ADDRESS3>
	<PRODUCTNAME></PRODUCTNAME>
	<STATEMENTDATE></STATEMENTDATE>
	<APR></APR>
	<PAYMENTDUEDATE></PAYMENTDUEDATE>
	<OPENINGBALANCE>0.00</OPENINGBALANCE>
	<TRANSACTIONDATE>2023-01-10T00:00:00</TRANSACTIONDATE>
	<POSTINGDATE>2023-01-10T00:00:00</POSTINGDATE>
	<DESCRIPTIONREFERENCE>Fed On Chip Fee</DESCRIPTIONREFERENCE>
	<TRANSACTIONAMOUNTUSD>160.00</TRANSACTIONAMOUNTUSD>
	<TRANSACTIONAMOUNTPKR>160.00</TRANSACTIONAMOUNTPKR>
	<RUNNINGBALANCEPKR>36307.40</RUNNINGBALANCEPKR>
	<CLOSINGBALANCEDATE></CLOSINGBALANCEDATE>
	<PROFIT_RECOVERED></PROFIT_RECOVERED>
	<MWM_PAYMENT></MWM_PAYMENT>
	<ISL_CONV_FLAG></ISL_CONV_FLAG>
</Statement>
                        </DtStatement>";
            System.Xml.Serialization.XmlSerializer xmlSerializer = new System.Xml.Serialization.XmlSerializer(typeof(DtStatement));
            DtStatement dtStatement = null;
            List<List<string>> tableBodyData;
            using (var strReader = new StringReader(s))
            {
                using (var reader = XmlReader.Create(strReader))
                {
                    dtStatement = (DtStatement)xmlSerializer.Deserialize(reader);
					tableBodyData = dtStatement.Statement.Select(x => new List<string>
					{
								(string.IsNullOrEmpty(x.TRANSACTIONDATE)?"-----":Convert.ToDateTime(x.TRANSACTIONDATE).ToString("MM/dd/yyyy hh:mm tt")),
								(string.IsNullOrEmpty(x.DESCRIPTIONREFERENCE)?"-----":x.DESCRIPTIONREFERENCE),
								(string.IsNullOrEmpty(x.TRANSACTIONAMOUNTPKR)?"-----":Convert.ToDecimal(x.TRANSACTIONAMOUNTPKR).ToString("N"))
                    }).ToList();
                }
            }

            PDFDesign pdf = new PDFDesign();
            var transactionDate = dtStatement.Statement[0].TRANSACTIONDATE;
            var descriptionReference = dtStatement.Statement[0].DESCRIPTIONREFERENCE;
            var transactionAmount = dtStatement.Statement[0].TRANSACTIONAMOUNTPKR;
            Random rand = new Random();
            int password = rand.Next(1000, 9999);
            string imagePath = AppDomain.CurrentDomain.BaseDirectory + "Uploads";
            string filePath = AppDomain.CurrentDomain.BaseDirectory + "Uploads\\abc.pdf";
            var isTableExist = true;

            TableDefaultProps tableDefaultProps = new TableDefaultProps()
            {
                ColumnAlign = ParagraphAlignment.Center,
                ColumnSize = "6.50cm",
                ColumnColor = Colors.White
            };
      
            TableData tableHeaderData = new TableData()
            {
                TableProps = new List<TableProps>()
                        {
                            new TableProps(tableDefaultProps)
                            {
                                ColumnName = "Date",
								
                            },
                            new TableProps(tableDefaultProps)
                            {
                                ColumnName = "Description/Reference",
                            },
                            new TableProps(tableDefaultProps)
                            {
                                ColumnName = "Amount",

                            }
                        },
                RowColor = PDFDesign.Blue,
                RowAlignment = ParagraphAlignment.Center
            };

            TableData topTablesHeaderData = new TableData()
            {
                TableProps = new List<TableProps>()
                        {
                            new TableProps(tableDefaultProps)
                            {
                                ColumnName = "Date",
                                //ColumnSize = "4cm"
                            },
                            new TableProps(tableDefaultProps)
                            {
                                ColumnName = "Description/Reference",
								
                                //ColumnSize = "7cm"
                            },
                            new TableProps(tableDefaultProps)
                            {
                                ColumnName = "Amount",
                                //ColumnSize = "5cm"
                            }
                        },
                RowColor = Colors.White,
                RowAlignment = ParagraphAlignment.Right
            };

			List<List<TopTable>> topTableBodyData = new List<List<TopTable>>() {
						new List<TopTable>(){
							new TopTable(){
								Text = "Date",
								Color = Colors.Black,
								isBold = true,

							},
							new TopTable()
							{
								Text = transactionDate,
								Color = Colors.Black,

							},
							new TopTable()
							{
								Text = "Description/Reference",
								Color = PDFDesign.Green,
								isBold = true,
							},
							new TopTable()
							{
								Text = descriptionReference,
								Color = PDFDesign.Green,
								isBold = true,
							}

						},

						new List<TopTable>(){
							new TopTable(){
								Text = "Amount",
								Color = Colors.Black,
								isBold = true,
							},
							new TopTable()
							{
								Text = transactionAmount,
								Color = Colors.Black,

							}
						},
                        
                    };

            //List<string> paragraphList = new List<string>() {
            //            $"YOUR STATEMENT",
            //            $"{FromDate}",
            //            $"{ToDate}",
            //            $"{BranchNo}",
            //            $"{RowNumber}",
            //            $"{DrcRind}",
            //            $"{Balance}"
            //        };

            List<string> paragraphList = new List<string>() {
                        $"",
                        $"",
                        $"",
                        $"",
                        $"",
                        $"",
                        $""
                    };

            var isDocCreated = pdf.CreateDocumentForTransHist(
                   isTableExist,
                   paragraphList,
                   tableHeaderData,
                   tableBodyData,
                   topTablesHeaderData,
                   topTableBodyData,
                   filePath,
                   imagePath,
                   DateTime.Now.ToString("MM/dd/yyyy"),
                   DateTime.Now.ToString("MM/dd/yyyy"),
                   password.ToString()
               );

            Console.ReadLine();
        }
    }
}
